version: "3.7"

services:
  postgres:
    image: postgres
    container_name: restaurant-database
    environment:
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: restaurant
      POSTGRES_DB: restaurant
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres 
    restart: always

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-api
    env_file: .env.docker
    ports: 
      - 2000:2000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  pgdata: 
    driver: local